import { useState, useEffect } from 'react';
import { FileBox, Download, Bot, User } from 'lucide-react';
import { timeAgo } from '../utils/time';

interface FileMeta {
  id: number;
  agent_id: string;
  filename: string;
  mimetype: string;
  size: number;
  source: string;
  description: string;
  created_at: string;
}

interface FilesPanelProps {
  agentId: string;
}

function formatSize(bytes: number): string {
  if (bytes < 1024) return `${bytes}B`;
  if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)}KB`;
  return `${(bytes / (1024 * 1024)).toFixed(1)}MB`;
}

function FilesPanel({ agentId }: FilesPanelProps) {
  const [files, setFiles] = useState<FileMeta[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    fetch(`/api/agents/${agentId}/files`)
      .then((res) => res.json())
      .then((data) => {
        setFiles(Array.isArray(data) ? data : []);
        setLoading(false);
      })
      .catch(() => setLoading(false));
  }, [agentId]);

  if (loading) return null;
  if (files.length === 0) return null;

  const claudeFiles = files.filter((f) => f.source === 'claude');
  const userFiles = files.filter((f) => f.source !== 'claude');

  const renderFile = (file: FileMeta) => (
    <div key={file.id} className="flex items-center gap-3 p-2 rounded-lg hover:bg-dark-850 transition-colors group">
      <div className="shrink-0">
        {file.source === 'claude' ? (
          <Bot size={14} className="text-lumi-400" />
        ) : (
          <User size={14} className="text-dark-400" />
        )}
      </div>
      <div className="flex-1 min-w-0">
        <p className="text-sm text-dark-200 truncate">{file.filename}</p>
        <div className="flex items-center gap-2 text-xs text-dark-500">
          <span>{formatSize(file.size)}</span>
          <span>&middot;</span>
          <span>{timeAgo(file.created_at)}</span>
          {file.description && (
            <>
              <span>&middot;</span>
              <span className="truncate">{file.description}</span>
            </>
          )}
        </div>
      </div>
      <a
        href={`/api/agents/${agentId}/files/${file.id}`}
        download={file.filename}
        className="shrink-0 p-1.5 text-dark-500 hover:text-lumi-400 opacity-0 group-hover:opacity-100 transition-all"
        title="Download"
      >
        <Download size={14} />
      </a>
    </div>
  );

  return (
    <div className="bg-dark-900 border border-dark-800 rounded-xl overflow-hidden">
      <div className="px-5 py-4 border-b border-dark-800">
        <h2 className="text-sm font-semibold text-dark-300 uppercase tracking-wide flex items-center gap-2">
          <FileBox size={14} />
          Files & Artefacts
        </h2>
      </div>
      <div className="p-3 space-y-3">
        {claudeFiles.length > 0 && (
          <div>
            <h3 className="text-xs font-semibold text-dark-400 uppercase tracking-wide mb-1.5 px-2">
              Generated by Claude
            </h3>
            {claudeFiles.map(renderFile)}
          </div>
        )}
        {userFiles.length > 0 && (
          <div>
            <h3 className="text-xs font-semibold text-dark-400 uppercase tracking-wide mb-1.5 px-2">
              Uploaded by User
            </h3>
            {userFiles.map(renderFile)}
          </div>
        )}
      </div>
    </div>
  );
}

export default FilesPanel;
