package com.claudemanager.app.data.models

import com.google.gson.annotations.SerializedName

/**
 * Metadata for a file attachment associated with an agent.
 * Does not include the binary data itself -- use the download endpoint for that.
 */
data class FileInfo(
    @SerializedName("id")
    val id: Long,

    @SerializedName("agent_id")
    val agentId: String,

    @SerializedName("filename")
    val filename: String,

    @SerializedName("mimetype")
    val mimetype: String,

    @SerializedName("size")
    val size: Long,

    @SerializedName("source")
    val source: String = "user",

    @SerializedName("description")
    val description: String? = null,

    @SerializedName("created_at")
    val createdAt: String
) {
    /**
     * Whether this file was uploaded by the user (from the dashboard/app)
     * vs. generated by the Claude agent.
     */
    val isFromUser: Boolean
        get() = source == "user"

    /**
     * Human-readable file size string.
     */
    val formattedSize: String
        get() = when {
            size < 1024 -> "$size B"
            size < 1024 * 1024 -> "${size / 1024} KB"
            else -> String.format("%.1f MB", size / (1024.0 * 1024.0))
        }
}
