package com.claudemanager.app.ui.detail.components

import androidx.compose.foundation.background
import androidx.compose.foundation.clickable
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Box
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Row
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.layout.size
import androidx.compose.foundation.layout.width
import androidx.compose.foundation.lazy.LazyColumn
import androidx.compose.foundation.lazy.items
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.filled.ArrowDownward
import androidx.compose.material.icons.filled.ArrowUpward
import androidx.compose.material.icons.filled.AudioFile
import androidx.compose.material.icons.filled.Code
import androidx.compose.material.icons.filled.Description
import androidx.compose.material.icons.filled.Image
import androidx.compose.material.icons.filled.InsertDriveFile
import androidx.compose.material.icons.filled.PictureAsPdf
import androidx.compose.material.icons.filled.TableChart
import androidx.compose.material.icons.filled.VideoFile
import androidx.compose.material3.FilterChip
import androidx.compose.material3.FilterChipDefaults
import androidx.compose.material3.HorizontalDivider
import androidx.compose.material3.Icon
import androidx.compose.material3.MaterialTheme
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.runtime.getValue
import androidx.compose.runtime.mutableStateOf
import androidx.compose.runtime.remember
import androidx.compose.runtime.setValue
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.draw.clip
import androidx.compose.ui.graphics.vector.ImageVector
import androidx.compose.ui.text.style.TextOverflow
import androidx.compose.ui.unit.dp
import com.claudemanager.app.data.models.FileInfo
import com.claudemanager.app.ui.theme.LumiCard
import com.claudemanager.app.ui.theme.LumiInfo
import com.claudemanager.app.ui.theme.LumiOnSurface
import com.claudemanager.app.ui.theme.LumiOnSurfaceSecondary
import com.claudemanager.app.ui.theme.LumiOnSurfaceTertiary
import com.claudemanager.app.ui.theme.LumiPurple500
import com.claudemanager.app.util.TimeUtils

/**
 * Sort field for the files panel.
 */
private enum class FileSortField { NAME, DATE }

/**
 * Panel displaying files attached to an agent, split into "Generated by Agent"
 * and "Uploaded by User" sections, with sort controls.
 *
 * @param files List of file metadata for this agent.
 * @param onFileClick Callback when a file is tapped (receives file ID for download URL).
 */
@Composable
fun FilesPanel(
    files: List<FileInfo>,
    onFileClick: (Long) -> Unit,
    modifier: Modifier = Modifier
) {
    if (files.isEmpty()) {
        Box(
            modifier = modifier.padding(32.dp),
            contentAlignment = Alignment.Center
        ) {
            Text(
                text = "No files attached",
                style = MaterialTheme.typography.bodyLarge,
                color = LumiOnSurfaceTertiary
            )
        }
        return
    }

    var sortField by remember { mutableStateOf(FileSortField.DATE) }
    var sortAscending by remember { mutableStateOf(false) } // newest first by default

    fun sortFiles(list: List<FileInfo>): List<FileInfo> {
        return when (sortField) {
            FileSortField.NAME -> if (sortAscending) list.sortedBy { it.filename.lowercase() }
                else list.sortedByDescending { it.filename.lowercase() }
            FileSortField.DATE -> {
                val sorted = list.sortedBy { TimeUtils.parseIso(it.createdAt)?.time ?: 0L }
                if (sortAscending) sorted else sorted.reversed()
            }
        }
    }

    val agentFiles = sortFiles(files.filter { !it.isFromUser })
    val userFiles = sortFiles(files.filter { it.isFromUser })

    LazyColumn(
        modifier = modifier.padding(horizontal = 16.dp),
        verticalArrangement = Arrangement.spacedBy(0.dp)
    ) {
        // Sort controls
        item {
            Spacer(modifier = Modifier.height(12.dp))
            Row(
                modifier = Modifier.fillMaxWidth(),
                horizontalArrangement = Arrangement.spacedBy(8.dp),
                verticalAlignment = Alignment.CenterVertically
            ) {
                Text(
                    text = "Sort:",
                    style = MaterialTheme.typography.labelMedium,
                    color = LumiOnSurfaceTertiary
                )
                FilterChip(
                    selected = sortField == FileSortField.NAME,
                    onClick = {
                        if (sortField == FileSortField.NAME) {
                            sortAscending = !sortAscending
                        } else {
                            sortField = FileSortField.NAME
                            sortAscending = true
                        }
                    },
                    label = { Text("Name", style = MaterialTheme.typography.labelSmall) },
                    leadingIcon = if (sortField == FileSortField.NAME) {
                        {
                            Icon(
                                imageVector = if (sortAscending) Icons.Default.ArrowUpward else Icons.Default.ArrowDownward,
                                contentDescription = if (sortAscending) "Ascending" else "Descending",
                                modifier = Modifier.size(14.dp)
                            )
                        }
                    } else null,
                    colors = FilterChipDefaults.filterChipColors(
                        selectedContainerColor = LumiPurple500.copy(alpha = 0.2f),
                        selectedLabelColor = LumiPurple500,
                        selectedLeadingIconColor = LumiPurple500,
                        containerColor = LumiCard,
                        labelColor = LumiOnSurfaceSecondary
                    )
                )
                FilterChip(
                    selected = sortField == FileSortField.DATE,
                    onClick = {
                        if (sortField == FileSortField.DATE) {
                            sortAscending = !sortAscending
                        } else {
                            sortField = FileSortField.DATE
                            sortAscending = false
                        }
                    },
                    label = { Text("Date", style = MaterialTheme.typography.labelSmall) },
                    leadingIcon = if (sortField == FileSortField.DATE) {
                        {
                            Icon(
                                imageVector = if (sortAscending) Icons.Default.ArrowUpward else Icons.Default.ArrowDownward,
                                contentDescription = if (sortAscending) "Ascending" else "Descending",
                                modifier = Modifier.size(14.dp)
                            )
                        }
                    } else null,
                    colors = FilterChipDefaults.filterChipColors(
                        selectedContainerColor = LumiPurple500.copy(alpha = 0.2f),
                        selectedLabelColor = LumiPurple500,
                        selectedLeadingIconColor = LumiPurple500,
                        containerColor = LumiCard,
                        labelColor = LumiOnSurfaceSecondary
                    )
                )
            }
            Spacer(modifier = Modifier.height(4.dp))
        }

        // Agent-generated files
        if (agentFiles.isNotEmpty()) {
            item {
                Spacer(modifier = Modifier.height(8.dp))
                Text(
                    text = "Generated by Agent",
                    style = MaterialTheme.typography.titleSmall,
                    color = LumiOnSurfaceSecondary
                )
                Spacer(modifier = Modifier.height(8.dp))
            }

            items(agentFiles, key = { it.id }) { file ->
                FileItem(file = file, onClick = { onFileClick(file.id) })
                HorizontalDivider(
                    color = LumiCard,
                    thickness = 1.dp,
                    modifier = Modifier.padding(start = 40.dp)
                )
            }
        }

        // User-uploaded files
        if (userFiles.isNotEmpty()) {
            item {
                Spacer(modifier = Modifier.height(16.dp))
                Text(
                    text = "Uploaded by User",
                    style = MaterialTheme.typography.titleSmall,
                    color = LumiOnSurfaceSecondary
                )
                Spacer(modifier = Modifier.height(8.dp))
            }

            items(userFiles, key = { it.id }) { file ->
                FileItem(file = file, onClick = { onFileClick(file.id) })
                HorizontalDivider(
                    color = LumiCard,
                    thickness = 1.dp,
                    modifier = Modifier.padding(start = 40.dp)
                )
            }
        }

        item { Spacer(modifier = Modifier.height(16.dp)) }
    }
}

/**
 * A single file item showing icon, filename, size, formatted date, and relative age.
 */
@Composable
private fun FileItem(file: FileInfo, onClick: () -> Unit) {
    Row(
        modifier = Modifier
            .fillMaxWidth()
            .clickable(onClick = onClick)
            .padding(vertical = 10.dp),
        verticalAlignment = Alignment.CenterVertically
    ) {
        // File type icon
        Icon(
            imageVector = mimeTypeIcon(file.mimetype),
            contentDescription = file.mimetype,
            tint = mimeTypeColor(file.mimetype),
            modifier = Modifier.size(24.dp)
        )

        Spacer(modifier = Modifier.width(12.dp))

        Column(modifier = Modifier.weight(1f)) {
            Text(
                text = file.filename,
                style = MaterialTheme.typography.bodyMedium,
                color = LumiOnSurface,
                maxLines = 1,
                overflow = TextOverflow.Ellipsis
            )
            Row {
                Text(
                    text = file.formattedSize,
                    style = MaterialTheme.typography.labelSmall,
                    color = LumiOnSurfaceTertiary
                )
                Spacer(modifier = Modifier.width(8.dp))
                Text(
                    text = TimeUtils.formatTimestamp(file.createdAt),
                    style = MaterialTheme.typography.labelSmall,
                    color = LumiOnSurfaceTertiary
                )
                Spacer(modifier = Modifier.width(6.dp))
                Text(
                    text = "(${TimeUtils.timeAgo(file.createdAt)})",
                    style = MaterialTheme.typography.labelSmall,
                    color = LumiOnSurfaceTertiary.copy(alpha = 0.7f)
                )
            }
        }
    }
}

/**
 * Returns an appropriate Material icon for the given MIME type.
 */
private fun mimeTypeIcon(mimetype: String): ImageVector = when {
    mimetype.startsWith("image/") -> Icons.Default.Image
    mimetype.startsWith("video/") -> Icons.Default.VideoFile
    mimetype.startsWith("audio/") -> Icons.Default.AudioFile
    mimetype == "application/pdf" -> Icons.Default.PictureAsPdf
    mimetype.contains("spreadsheet") || mimetype.contains("csv") || mimetype.contains("excel") ->
        Icons.Default.TableChart
    mimetype.contains("json") || mimetype.contains("javascript") || mimetype.contains("xml") ||
        mimetype.contains("html") || mimetype.contains("css") || mimetype.contains("typescript") ->
        Icons.Default.Code
    mimetype.startsWith("text/") -> Icons.Default.Description
    else -> Icons.Default.InsertDriveFile
}

/**
 * Returns a tint color for the file icon based on MIME type category.
 */
private fun mimeTypeColor(mimetype: String): androidx.compose.ui.graphics.Color = when {
    mimetype.startsWith("image/") -> LumiPurple500
    mimetype.startsWith("video/") -> LumiPurple500
    mimetype == "application/pdf" -> androidx.compose.ui.graphics.Color(0xFFEF4444)
    mimetype.contains("json") || mimetype.contains("javascript") || mimetype.contains("xml") ->
        androidx.compose.ui.graphics.Color(0xFFF59E0B)
    mimetype.startsWith("text/") -> LumiInfo
    else -> LumiOnSurfaceSecondary
}
